### ISSUE TITLE
CSS gradients：你知道的和你不知道的

### ISSUE THREAD

**Issue by akira-cn** [akira-cn/FE_You_dont_know#22]
在现代浏览器中，渐变（gradients）是一系列比较有用的CSS属性值。

渐变又分为3种：

- 线性渐变 linear-gradient
- 径向渐变 radial-gradient
- 圆锥渐变 conic-gradient

渐变不是CSS属性，而是属性值，在浏览器渲染的时候，被解析为图形，所以它可以应用在background-image、border-image、list-style-image、mask等能够使用图片的CSS属性上。

最常用的当然是background-image。

```html
<div class="block"></div>
```

```css
.block {
  width: 100px;
  height: 100px;
  background-image: linear-gradient(to right, red, yellow);
}
```

上面的代码创建了一个带有渐变色背景的div元素：

![](https://p0.ssl.qhimg.com/t01c7c83db18937afb7.jpg)

如果我们要让边框渐变，我们可以设置border-image:

```css
.block {
  width: 100px;
  height: 100px;
  background-image: linear-gradient(to right, red, yellow);
  border: solid 10px;
  border-image: linear-gradient(to right, blue, green) 1;
}
```

![](https://p4.ssl.qhimg.com/t01b7edd502264c180a.jpg)

一个比较少见的用法是，渐变还可以设置list-style-image:

```html
<ul>
  <li>1</li>
  <li>2</li>
  <li>3</li>
  <li>4</li>
  <li>5</li>
  <li>6</li>
</ul>
```

```css
li:nth-child(2n) {
  list-style-image: linear-gradient(to right, blue, green);
}

li:nth-child(2n+1) {
  list-style-image: linear-gradient(to right, red, yellow);
}
```

![](https://p4.ssl.qhimg.com/t0173e8e2ed04debaed.jpg)

由于渐变视为图片，`background-size`、`background-position`、`background-repeat`对它都有效，我们就可以用它来绘制一些有趣的图案。

```css
.block {
  width: 300px;
  height: 300px;
  background-image: linear-gradient(45deg, black 50%, transparent 0);
  background-size: 10% 10%;
}
```

![](https://p1.ssl.qhimg.com/t011e768bd31c7ffc4e.jpg)

```css
.block {
  width: 300px;
  height: 300px;
  background-image: linear-gradient(to bottom, grey 50%, black 0),
    linear-gradient(to bottom, black 50%, grey 0),
    linear-gradient(to bottom, grey 50%, black 0),
    linear-gradient(to bottom, black 50%, grey 0);
  background-size: 25% 25%;
  background-position: 0 0, 75px 0, 150px 0, 225px 0;
  background-repeat: repeat-y;
}
```

![](https://p0.ssl.qhimg.com/t01c4597a9b46ac34ca.jpg)

我们还可以用渐变来绘制饼图：

```html
<div class="pie"></div>
```

```css
.pie {
  display: inline-block;
  width: 150px;
  height: 150px;
  border-radius: 50%;
  background-image: linear-gradient(30deg, red 38%, yellow 0),
    linear-gradient(-45deg, cyan 50%, blue 0),
    linear-gradient(-135deg, gray 50%, green 0),
    linear-gradient(135deg, black 50%, orange 0);
  background-position: 0 0, 0 100%, 100% 100%, 100% 0;
  background-size: 50% 50%;
  background-repeat: no-repeat;
}
```

上面的代码是用线性渐变绘制的饼图。

![](https://p3.ssl.qhimg.com/t0142f8c6b56cb75e89.jpg)

当然如果用圆锥渐变就更简单了：

```css
.pie {
  display: inline-block;
  width: 150px;
  height: 150px;
  border-radius: 50%;
  background-image: conic-gradient(red 90deg, orange 90deg, orange 180deg, yellow 180deg, yellow 210deg, green 210deg, green 270deg, blue 270deg);
}
```

![](https://p3.ssl.qhimg.com/t0159d766e67a067143.jpg)

如果用渐变配合mask（遮罩）属性，可以用来做一些特殊的效果：

```html
<img src="https://p1.ssl.qhimg.com/t0182f688227da11a79.jpg">
```

```css
img {
  -webkit-mask: radial-gradient(#000, transparent 50%);
}
```

![](https://p1.ssl.qhimg.com/t0181bdccf117389142.jpg)

如果再配合动画就更有趣了：

```js
function animate({target, prop, duration, start, end, easing, interpolate} = {}) {
  const startTime = Date.now();

  return new Promise((resolve) => {
    function update() {
      const t = Date.now() - startTime;
      const p = Math.min(t / duration, 1);

      target.style[prop] = interpolate(start, end, easing ? easing(p) : p);
      if(p < 1) {
        requestAnimationFrame(update);
      } else {
        resolve(p);
      }
    }
    update();
  });
}

const img = document.querySelector('img');

animate({
  target: img,
  prop: 'webkitMask',
  duration: 1000,
  start: 0,
  end: 100,
  interpolate(start, end, p) {
    const v = start * (1 - p) + end * p;
    return `linear-gradient(to right, #000 ${v}%, transparent 0) 0/20px`
  }
});
```

![](https://p5.ssl.qhimg.com/t01c2ce796bd4bc97b2.gif)
